// flow-typed signature: 19a69ab6753e352851adc4b1fe583bbc
// flow-typed version: <<STUB>>/babel-plugin-react-intl_v^4.1.7/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl/dist/index' {
  declare module.exports: $Exports<'babel-plugin-react-intl/dist'>;
}
declare module 'babel-plugin-react-intl/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/dist'>;
}
