// flow-typed signature: 2ca0e2d4e15ee7ea69fa37394403a755
// flow-typed version: <<STUB>>/babel-flow-types_v1.2.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-flow-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-flow-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'babel-flow-types/index' {
  declare module.exports: $Exports<'babel-flow-types'>;
}
declare module 'babel-flow-types/index.js' {
  declare module.exports: $Exports<'babel-flow-types'>;
}
