// flow-typed signature: bc71e4124ffd30d0520dd26e3948b3e2
// flow-typed version: <<STUB>>/intl-messageformat-parser_v^3.0.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intl-messageformat-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intl-messageformat-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intl-messageformat-parser/build' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist/normalize' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist/parser' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist/printer' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intl-messageformat-parser/build.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/build'>;
}
declare module 'intl-messageformat-parser/dist/index' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist'>;
}
declare module 'intl-messageformat-parser/dist/index.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist'>;
}
declare module 'intl-messageformat-parser/dist/normalize.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist/normalize'>;
}
declare module 'intl-messageformat-parser/dist/parser.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist/parser'>;
}
declare module 'intl-messageformat-parser/dist/printer.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist/printer'>;
}
declare module 'intl-messageformat-parser/dist/types.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist/types'>;
}
