// flow-typed signature: a96516a19a93c0dcf1c4a6e23c4e61f2
// flow-typed version: <<STUB>>/jest_v24.8.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest/bin/jest' {
  declare module.exports: any;
}

declare module 'jest/build/jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest/bin/jest.js' {
  declare module.exports: $Exports<'jest/bin/jest'>;
}
declare module 'jest/build/jest.js' {
  declare module.exports: $Exports<'jest/build/jest'>;
}
